// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: trade.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Message Trading Channel state definition
public struct TradeState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var channelID: Data = Data()

  public var state: Core_State {
    get {return _state ?? Core_State()}
    set {_state = newValue}
  }
  /// Returns true if `state` has been explicitly set.
  public var hasState: Bool {return self._state != nil}
  /// Clears the value of `state`. Subsequent reads from it will return its default value.
  public mutating func clearState() {self._state = nil}

  public var stateHash: Data = Data()

  public var stateHashSigs: [Core_Signature] = []

  public var safety: Core_Decimal {
    get {return _safety ?? Core_Decimal()}
    set {_safety = newValue}
  }
  /// Returns true if `safety` has been explicitly set.
  public var hasSafety: Bool {return self._safety != nil}
  /// Clears the value of `safety`. Subsequent reads from it will return its default value.
  public mutating func clearSafety() {self._safety = nil}

  public var marginCall: Core_SignedMarginCall {
    get {return _marginCall ?? Core_SignedMarginCall()}
    set {_marginCall = newValue}
  }
  /// Returns true if `marginCall` has been explicitly set.
  public var hasMarginCall: Bool {return self._marginCall != nil}
  /// Clears the value of `marginCall`. Subsequent reads from it will return its default value.
  public mutating func clearMarginCall() {self._marginCall = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _state: Core_State? = nil
  fileprivate var _safety: Core_Decimal? = nil
  fileprivate var _marginCall: Core_SignedMarginCall? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension TradeState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "TradeState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "channel_id"),
    2: .same(proto: "state"),
    3: .standard(proto: "state_hash"),
    4: .standard(proto: "state_hash_sigs"),
    5: .same(proto: "safety"),
    6: .standard(proto: "margin_call"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.channelID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._state) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.stateHash) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.stateHashSigs) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._safety) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._marginCall) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.channelID.isEmpty {
      try visitor.visitSingularBytesField(value: self.channelID, fieldNumber: 1)
    }
    try { if let v = self._state {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.stateHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.stateHash, fieldNumber: 3)
    }
    if !self.stateHashSigs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.stateHashSigs, fieldNumber: 4)
    }
    try { if let v = self._safety {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._marginCall {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: TradeState, rhs: TradeState) -> Bool {
    if lhs.channelID != rhs.channelID {return false}
    if lhs._state != rhs._state {return false}
    if lhs.stateHash != rhs.stateHash {return false}
    if lhs.stateHashSigs != rhs.stateHashSigs {return false}
    if lhs._safety != rhs._safety {return false}
    if lhs._marginCall != rhs._marginCall {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
